/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.androidsnmp.manager.gui;

import com.androidsnmp.manager.models.ManagedDevice;
import java.awt.LayoutManager;

/**
 *
 * @author brnunes
 */
public class PhonePanel extends javax.swing.JPanel {
    protected boolean mAllowLayoutChange;
    private ManagedDevice device;
    
    /**
     * Creates new form PhonePanel
     */
    public PhonePanel(ManagedDevice device) {
        this.device = device;
        mAllowLayoutChange=true;
        initComponents();
        mAllowLayoutChange=false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gpsLabel = new javax.swing.JLabel();
        networkLabel = new javax.swing.JLabel();
        bluetoothLabel = new javax.swing.JLabel();
        batteryStatusLabel = new javax.swing.JLabel();
        batteryLevelLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ipLabel = new javax.swing.JLabel();
        modelLabel = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();
        upTimeLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(640, 360));

        gpsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/androidsnmp/manager/gui/res/gps_icon.png"))); // NOI18N
        gpsLabel.setToolTipText("Get GPS Status");
        gpsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gpsLabelMouseClicked(evt);
            }
        });

        networkLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/androidsnmp/manager/gui/res/gps_icon.png"))); // NOI18N
        networkLabel.setToolTipText("Get Network Status");
        networkLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                networkLabelMouseClicked(evt);
            }
        });

        bluetoothLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/androidsnmp/manager/gui/res/bluetooth_icon.png"))); // NOI18N
        bluetoothLabel.setToolTipText("Get  Bluetooth Status");
        bluetoothLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bluetoothLabelMouseClicked(evt);
            }
        });

        batteryStatusLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/androidsnmp/manager/gui/res/gps_icon.png"))); // NOI18N
        batteryStatusLabel.setToolTipText("Get Battery Status");
        batteryStatusLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                batteryStatusLabelMouseClicked(evt);
            }
        });

        batteryLevelLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/androidsnmp/manager/gui/res/gps_icon.png"))); // NOI18N
        batteryLevelLabel.setToolTipText("Get Battery Level");
        batteryLevelLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                batteryLevelLabelMouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setPreferredSize(new java.awt.Dimension(360, 200));
        jScrollPane1.setViewportView(jTable1);

        ipLabel.setText("IP: ");

        modelLabel.setText("Model:");

        versionLabel.setText("Version:");

        upTimeLabel.setText("Up time:");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(gpsLabel)
                            .addGap(0, 0, 0)
                            .addComponent(networkLabel)
                            .addGap(0, 0, 0)
                            .addComponent(bluetoothLabel)
                            .addGap(0, 0, 0)
                            .addComponent(batteryStatusLabel)
                            .addGap(0, 0, 0)
                            .addComponent(batteryLevelLabel))
                        .addComponent(ipLabel)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(upTimeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(modelLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(versionLabel)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel5))))
                .addGap(280, 280, 280))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gpsLabel)
                    .addComponent(networkLabel)
                    .addComponent(bluetoothLabel)
                    .addComponent(batteryStatusLabel)
                    .addComponent(batteryLevelLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelLabel)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(versionLabel)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upTimeLabel)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ipLabel))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void gpsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gpsLabelMouseClicked
        device.updateGPSStatus();
    }//GEN-LAST:event_gpsLabelMouseClicked

    public void setGPSStatus() {
        
    }
    
    private void networkLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_networkLabelMouseClicked
        device.updateNetworkStatus();
    }//GEN-LAST:event_networkLabelMouseClicked

    public void setNetworkStatus() {
        
    }
    
    private void bluetoothLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bluetoothLabelMouseClicked
        device.updateBluetoothStatus();
    }//GEN-LAST:event_bluetoothLabelMouseClicked

    public void setBluetoothStatus() {
        
    }
    
    private void batteryStatusLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batteryStatusLabelMouseClicked
        device.updateBatteryStatus();
    }//GEN-LAST:event_batteryStatusLabelMouseClicked

    public void setBatteryStatus() {
        
    }
    
    private void batteryLevelLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batteryLevelLabelMouseClicked
        device.updateBatteryLevel();
    }
    
    public void setBatteryLevel() {
        
    }
    
    @Override
    public void setLayout(LayoutManager mgr) {
        if(mAllowLayoutChange) {
            super.setLayout(mgr);
        }
    }//GEN-LAST:event_batteryLevelLabelMouseClicked

    public void setIpLabel(String text) {
        ipLabel.setText("IP: " + text);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel batteryLevelLabel;
    private javax.swing.JLabel batteryStatusLabel;
    private javax.swing.JLabel bluetoothLabel;
    private javax.swing.JLabel gpsLabel;
    private javax.swing.JLabel ipLabel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JLabel networkLabel;
    private javax.swing.JLabel upTimeLabel;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration//GEN-END:variables
}
